#include "lexer/token.h"

namespace grav {

const char *tokenTypeName(TokenType type) {
    switch (type) {
        case TokenType::Identifier: return "identifier";
        case TokenType::IntLiteral: return "int literal";
        case TokenType::FloatLiteral: return "float literal";
        case TokenType::StringLiteral: return "string literal";
        case TokenType::KwInt: return "'int'";
        case TokenType::KwFloat: return "'float'";
        case TokenType::KwBool: return "'bool'";
        case TokenType::KwString: return "'string'";
        case TokenType::KwVoid: return "'void'";
        case TokenType::True: return "'true'";
        case TokenType::False: return "'false'";
        case TokenType::Null: return "'null'";
        case TokenType::Let: return "'let'";
        case TokenType::Const: return "'const'";
        case TokenType::Fn: return "'fn'";
        case TokenType::Class: return "'class'";
        case TokenType::Struct: return "'struct'";
        case TokenType::Enum: return "'enum'";
        case TokenType::Type: return "'type'";
        case TokenType::Sizeof: return "'sizeof'";
        case TokenType::Abstract: return "'abstract'";
        case TokenType::Interface: return "'interface'";
        case TokenType::Async: return "'async'";
        case TokenType::Await: return "'await'";
        case TokenType::Namespace: return "'namespace'";
        case TokenType::Constructor: return "'constructor'";
        case TokenType::Extends: return "'extends'";
        case TokenType::Implements: return "'implements'";
        case TokenType::New: return "'new'";
        case TokenType::Return: return "'return'";
        case TokenType::Static: return "'static'";
        case TokenType::Readonly: return "'readonly'";
        case TokenType::Public: return "'public'";
        case TokenType::Private: return "'private'";
        case TokenType::Protected: return "'protected'";
        case TokenType::Self: return "'self'";
        case TokenType::If: return "'if'";
        case TokenType::Else: return "'else'";
        case TokenType::While: return "'while'";
        case TokenType::For: return "'for'";
        case TokenType::Do: return "'do'";
        case TokenType::Switch: return "'switch'";
        case TokenType::Case: return "'case'";
        case TokenType::Default: return "'default'";
        case TokenType::Match: return "'match'";
        case TokenType::Break: return "'break'";
        case TokenType::Continue: return "'continue'";
        case TokenType::In: return "'in'";
        case TokenType::As: return "'as'";
        case TokenType::Is: return "'is'";
        case TokenType::Colon: return "':'";
        case TokenType::ColonColon: return "'::'";
        case TokenType::Semicolon: return "';'";
        case TokenType::Comma: return "','";
        case TokenType::Dot: return "'.'";
        case TokenType::DotDot: return "'..'";
        case TokenType::DotDotEq: return "'..='";
        case TokenType::Ellipsis: return "'...'";
        case TokenType::Assign: return "'='";
        case TokenType::Arrow: return "'->'";
        case TokenType::FatArrow: return "'=>'";
        case TokenType::At: return "'@'";
        case TokenType::Hash: return "'#'";
        case TokenType::Question: return "'?'";
        case TokenType::QuestionQuestion: return "'??'";
        case TokenType::QuestionDot: return "'?.'";
        case TokenType::LParen: return "'('";
        case TokenType::RParen: return "')'";
        case TokenType::LBrace: return "'{'";
        case TokenType::RBrace: return "'}'";
        case TokenType::LBracket: return "'['";
        case TokenType::RBracket: return "']'";
        case TokenType::Plus: return "'+'";
        case TokenType::Minus: return "'-'";
        case TokenType::Star: return "'*'";
        case TokenType::Slash: return "'/'";
        case TokenType::Percent: return "'%'";
        case TokenType::PlusPlus: return "'++'";
        case TokenType::MinusMinus: return "'--'";
        case TokenType::PlusEq: return "'+='";
        case TokenType::MinusEq: return "'-='";
        case TokenType::StarEq: return "'*='";
        case TokenType::SlashEq: return "'/='";
        case TokenType::PercentEq: return "'%='";
        case TokenType::EqEq: return "'=='";
        case TokenType::NotEq: return "'!='";
        case TokenType::Greater: return "'>'";
        case TokenType::Less: return "'<'";
        case TokenType::GreaterEq: return "'>='";
        case TokenType::LessEq: return "'<='";
        case TokenType::AmpAmp: return "'&&'";
        case TokenType::PipePipe: return "'||'";
        case TokenType::Bang: return "'!'";
        case TokenType::Amp: return "'&'";
        case TokenType::Pipe: return "'|'";
        case TokenType::Caret: return "'^'";
        case TokenType::Tilde: return "'~'";
        case TokenType::ShiftLeft: return "'<<'";
        case TokenType::ShiftRight: return "'>>'";
        case TokenType::AmpEq: return "'&='";
        case TokenType::PipeEq: return "'|='";
        case TokenType::CaretEq: return "'^='";
        case TokenType::ShiftLeftEq: return "'<<='";
        case TokenType::ShiftRightEq: return "'>>='";
        case TokenType::Unknown: return "unknown token";
        case TokenType::Invalid: return "invalid token";
        case TokenType::EndOfFile: return "end of file";
    }
    return "token";
}

} // namespace grav
